project:
  type: book
  output-dir: docs
  resources: 
  - "images/*"
  - "data/*"

book:
  title: "30DCC (2025)"
  author: "Lisa DeBruine"
  description: "Code and charts for the 2025 30-Day Chart Challenge"
  cover-image: images/logos/logo.png
  image: images/logos/logo.png
  favicon: images/logos/favicon.ico
  #cookie-consent: true
  google-analytics: "G-6NP3MF25W3"
  page-navigation: true
  search: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  repo-url: https://github.com/debruine/30DCC-2025/
  repo-branch: master
  repo-actions: [edit, issue, source]
#  downloads: [pdf, epub]
  # sidebar:
  #   style: docked
  #   background: light
  page-footer: 
    left: "CC-BY 2025, Lisa DeBruine" 
    right: 
      - icon: github
        href: https://github.com/debruine/30DCC-2025
  chapters:
    - index.qmd
    - part: "Comparisons"
      chapters:
      - 01-fractions.qmd
    - part: "Distributions"
    - part: "Relationships"
    - part: "Timeseries"
    - part: "Uncertainties"

bibliography: include/book.bib
csl: include/apa.csl

format:
  html:
    theme: 
      light: yeti
      dark: darkly
    code-link: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-copy: true
    # code-block-border-left: "#4864DB"
    highlight-style: a11y
    # monofont: Fira Code
    # mainfont: Open Sans
    css: include/style.css
    include-after-body: include/script.js

